/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Dimension;
import javax.swing.JInternalFrame;
import modelo.entidadUsuario;

/**
 *
 * @author GAMER
 */
public class principal extends javax.swing.JFrame {
ventaform fventas= new ventaform();
productoform fproducto=new productoform();
clienteform fcliente=new clienteform();
usuarioform fusuario= new usuarioform();
    public principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH); /** ete metodo es para que la ventana cubre toda la pantalla**/
    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaprincipal = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        form = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        fventa = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        clientef = new javax.swing.JMenuItem();
        productof = new javax.swing.JMenuItem();
        usuariof = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Banner tienda en línea (1).png"))); // NOI18N

        ventanaprincipal.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ventanaprincipalLayout = new javax.swing.GroupLayout(ventanaprincipal);
        ventanaprincipal.setLayout(ventanaprincipalLayout);
        ventanaprincipalLayout.setHorizontalGroup(
            ventanaprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaprincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ventanaprincipalLayout.setVerticalGroup(
            ventanaprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaprincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MENU1.png"))); // NOI18N
        jMenu1.setText("MENU");

        jMenuItem1.setText("Ayuda");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        form.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compras.png"))); // NOI18N
        jMenu2.setText("VENTA");

        fventa.setText("Generar venta");
        fventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fventaActionPerformed(evt);
            }
        });
        jMenu2.add(fventa);

        form.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/config.png"))); // NOI18N
        jMenu3.setText("MANTENIMIENTO");

        clientef.setText("cliente");
        clientef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientefActionPerformed(evt);
            }
        });
        jMenu3.add(clientef);

        productof.setText("producto");
        productof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productofActionPerformed(evt);
            }
        });
        jMenu3.add(productof);

        usuariof.setText("usuario");
        usuariof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariofActionPerformed(evt);
            }
        });
        jMenu3.add(usuariof);

        form.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/torta.png"))); // NOI18N
        jMenu4.setText("REPORTES");

        jMenuItem7.setText("Reporte de venta");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        form.add(jMenu4);

        setJMenuBar(form);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaprincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaprincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void fventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fventaActionPerformed
      ventaform vf= new ventaform();
      centrarventana(vf);
    }
    void centrarventana(JInternalFrame frame){/**los psrsmetros son el internal frame y se le da un nombre**/
      ventanaprincipal.add(frame);
        Dimension dimencion= ventanaprincipal.getSize();//dimencion del la entana principal
        Dimension fventas=  frame.getSize(); // dimencion ventana intena de venta
        frame.setLocation((dimencion.width- fventas.height )/2, (dimencion.height-fventas.width )/2);
   
      frame.show();
    }//GEN-LAST:event_fventaActionPerformed

    private void clientefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientefActionPerformed
       clienteform cf=new clienteform();
        centrarventana(cf);
       
    }//GEN-LAST:event_clientefActionPerformed

    private void productofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productofActionPerformed
      productoform pf=new productoform();
        centrarventana(pf);
    }//GEN-LAST:event_productofActionPerformed

    private void usuariofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariofActionPerformed
        usuarioform uf=new usuarioform();
        centrarventana(uf);
    }//GEN-LAST:event_usuariofActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       detalleVentaform dtv= new detalleVentaform();
        centrarventana(dtv);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem clientef;
    public static javax.swing.JMenuBar form;
    private javax.swing.JMenuItem fventa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem productof;
    private javax.swing.JMenuItem usuariof;
    public static javax.swing.JDesktopPane ventanaprincipal;
    // End of variables declaration//GEN-END:variables
}
