/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.UsurioDAO;
import modelo.cliente;
import modelo.clienteDAO;
import modelo.detalleventa;
import modelo.entidadUsuario;
import modelo.producto;
import modelo.productoDAO;
import modelo.venta;
import modelo.ventaDAO;
/**
 *
 * @author GAMER
 */
public final class ventaform extends javax.swing.JInternalFrame {
   clienteDAO cdao=new clienteDAO();
   cliente cliente=new cliente();
  producto pr=new producto();
  productoDAO prd= new productoDAO();
  venta vt=new venta();
  ventaDAO vtdao= new ventaDAO();
    entidadUsuario us=new entidadUsuario();
    UsurioDAO udao=new UsurioDAO();
  int idp;
  double pre;
  int cant;
  double totalpagar;
  venta v= new venta();
    ventaDAO vd= new ventaDAO();
    detalleventa dtv=new detalleventa();
        DefaultTableModel modelo= new DefaultTableModel();
       String vendedor= us.getUser();
    public ventaform() {
        
        initComponents();
    
       generarserie();
        fecha();

       }
    
    void fecha(){
    
     Calendar calendar= new GregorianCalendar();
        txtfechaventa.setText(""+ calendar.get(Calendar.YEAR)+"/"+calendar.get(Calendar.MONTH)+"/"+ calendar .get(Calendar.DAY_OF_MONTH));
    txtvendedor.setText(us.getUser());                         
    
    }
    
    void generarserie(){
    String  serie=vd.idventa();
        if (serie== null) {
            txtserie.setText("00001");
        }else{
        int incremen=Integer.parseInt(serie);
        incremen= incremen+1;
        txtserie.setText("00000"+ incremen);
       
        txtcodcliente.requestFocus();
        }
    }
    void vndedor(){
        logueo lo= new logueo();
        lo.validar();
        String user=us.getUser();
     String   vendedor=us.getUser();
        if (vendedor!=null) {
            txtvendedor.setText(user);
        }
       
          
        }

    
    
    
        
    
    
    
     
        
     


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtserie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtcodcliente = new javax.swing.JTextField();
        btnbuscliventa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtclienteventa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcodprod = new javax.swing.JTextField();
        btnbusprodven = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtprodventa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        btnagreventa = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtstokventa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        txtfechaventa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtvendedor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladetalle = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txttotalpagar = new javax.swing.JTextField();
        btngeventa = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("venta");

        jLabel1.setText("VENTAS OLIVO");

        jLabel2.setText("TODO L RELACIONADO CON ORNAMENTACION");

        jLabel3.setText("SERIE");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loguin.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtserie, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Cod cliente");

        txtcodcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodclienteActionPerformed(evt);
            }
        });

        btnbuscliventa.setText("buscar");
        btnbuscliventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscliventaActionPerformed(evt);
            }
        });

        jLabel6.setText("cliente");

        jLabel7.setText("cod. producto");

        btnbusprodven.setText("buscar");
        btnbusprodven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbusprodvenActionPerformed(evt);
            }
        });

        jLabel8.setText("producto");

        jLabel9.setText("precio");

        btnagreventa.setText("agregar");
        btnagreventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagreventaActionPerformed(evt);
            }
        });

        jLabel10.setText("Stock");

        jLabel11.setText("cantidad");

        txtfechaventa.setText("fecha");

        jLabel12.setText("vendedor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(246, 246, 246))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcodcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtprecio)
                                            .addComponent(txtcodprod)
                                            .addComponent(txtcantidad))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(240, 240, 240)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnbuscliventa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(txtfechaventa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel12))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnagreventa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(btnbusprodven)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtclienteventa)
                    .addComponent(txtprodventa)
                    .addComponent(txtstokventa)
                    .addComponent(txtvendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcodcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscliventa)
                    .addComponent(jLabel6)
                    .addComponent(txtclienteventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtcodprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbusprodven)
                    .addComponent(jLabel8)
                    .addComponent(txtprodventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnagreventa)
                    .addComponent(jLabel10)
                    .addComponent(txtstokventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfechaventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabladetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cod", "cod producto", "producto", "cantidad", "precio", "total"
            }
        ));
        jScrollPane2.setViewportView(tabladetalle);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel13.setText("total a pagar");

        btngeventa.setText("Generar venta");
        btngeventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngeventaActionPerformed(evt);
            }
        });

        btncancelar.setText("cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btngeventa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(txttotalpagar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txttotalpagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btngeventa)
                    .addComponent(btncancelar))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngeventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngeventaActionPerformed
        if (txttotalpagar.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "debe ingresar datos");
            
        }else{
         guardarventa();
  guardardetalleventa();
  actualizarStock();
            try {
                Rpdf();
            } catch (DocumentException ex) {
                Logger.getLogger(ventaform.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ventaform.class.getName()).log(Level.SEVERE, null, ex);
            }
  JOptionPane.showMessageDialog(this, "venta realizada con exito");
        nuevo();
        }
        
       
    }//GEN-LAST:event_btngeventaActionPerformed
  void  nuevo(){
      limpiarTAbla();
      txtserie.setText("");
  txtcodcliente.setText("");
  txtclienteventa.setText("");
  txtcodprod.setText("");
  txtprodventa.setText("");
  txtprecio.setText("");
  txtstokventa.setText("");
  txtcantidad.setText("");
  txtvendedor.setText("");
  txttotalpagar.setText("");
  txtcodcliente.requestFocus();
          
  
  
  }
          
    
    
    
    void limpiarTAbla(){
      for (int i = 0; i < modelo.getRowCount(); i++) {
          modelo.removeRow(i);
          i=i-1;
      }
  
  
  
  }
    
    
    
    void actualizarStock(){
      for (int i = 0; i < modelo.getRowCount(); i++) {
          idp= Integer.parseInt(tabladetalle.getValueAt(i, 1).toString());
          cant=Integer.parseInt(tabladetalle.getValueAt(i, 3).toString());
          pr=prd.BuscarPro(idp);
          int sa=(pr.getStock()- cant);
          prd.actualizarstock(sa, idp);
          
      }
  
  
  }
    
    
    
    void guardarventa(){
        
    int idv=01;
    int idc= cliente.getId_cliente();
    String serie=txtserie.getText();
    double monto=totalpagar;
    String fecha=txtfechaventa.getText();
    String estado="1";
    v.setId_cliente(idc);
    v.setId_vendedor(idv);
    v.setNumeroVenta(serie);
     v.setMonto(monto);
    v.setFechaventa(fecha);
    v.setEstado(estado);
   vd.guardarventa(v);
            
    }
    
    void guardardetalleventa(){
    String idv=vd.idventa();
   
        for (int i = 0; i < tabladetalle.getRowCount(); i++) {
             int idve=Integer.parseInt(idv);
            int idpr=Integer.parseInt(tabladetalle.getValueAt(i, 1).toString());
            int canti= Integer.parseInt(tabladetalle.getValueAt(i, 3).toString());
            double prec=Double.parseDouble(tabladetalle.getValueAt(i, 4).toString());
             dtv.setId_venta(idve);
             dtv.setId_producto(idpr);
             dtv.setCantidad(canti);
             dtv.setPrecioventa(prec);
             vd.guardardetaventa(dtv);
        
        }
            
    
    }
    
    
    
    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnbuscliventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscliventaActionPerformed
 
   buscarCliente();
   
    }//GEN-LAST:event_btnbuscliventaActionPerformed

    private void btnbusprodvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbusprodvenActionPerformed
   buscarproducto();
    }//GEN-LAST:event_btnbusprodvenActionPerformed

    private void btnagreventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagreventaActionPerformed
       agregarproducto();
    }//GEN-LAST:event_btnagreventaActionPerformed

    private void txtcodclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodclienteActionPerformed
   void agregarproducto(){
       double total;
       int cod=0;
   modelo=(DefaultTableModel)tabladetalle.getModel();
   
   idp= Integer.parseInt(txtcodprod.getText());
   String nom=txtprodventa.getText();
    pre=Double.parseDouble(txtprecio.getText());
    cod=cod+1;
  int canti;
       canti =Integer.parseInt(txtcantidad.getText());
       int stock=Integer.parseInt(txtstokventa.getText());
  total=canti*pre;
       ArrayList lista;
       lista = new ArrayList();
       if (stock>0) {
           
           lista.add(cod);
           lista.add(idp);
           lista.add(nom);
           lista.add(canti);
           lista.add(pre);
           lista.add(total);
           Object [] ob= new Object[6];
           ob[0]=lista.get(0);
           ob[1]=lista.get(1);
           ob[2]=lista.get(2);
           ob[3]=lista.get(3);
           ob[4]=lista.get(4);
           ob[5]=lista.get(5);
           
           modelo.addRow(ob);/** hay que agregar a la tabla el objeto**/
           tabladetalle.setModel(modelo);
           calculartotal();
           
       }else{
       JOptionPane.showMessageDialog(this," stock no disponible");
       
       }
       
   }
   void calculartotal(){
  totalpagar=0;
       for (int i = 0; i < tabladetalle.getRowCount(); i++) {
           cant=Integer.parseInt(tabladetalle.getValueAt(i, 3).toString());
           pre=Double.parseDouble(tabladetalle.getValueAt(i, 4).toString());
            
           totalpagar= totalpagar+(cant*pre);
       }
    txttotalpagar.setText(""+totalpagar);
   
   
   
   }
    
    
    
    public void buscarproducto(){
     
     if (txtcodprod.getText().equals("")) {
         JOptionPane.showMessageDialog(this,"ingrese el codigo del producto");
         
     }else{
       int id =Integer.parseInt(txtcodprod.getText());
    producto  pro=prd.BuscarPro(id);
   
         if (pro.getId_producto()!=0) {
             txtprodventa.setText(pro.getNombre());
             txtprecio. setText( ""+pro.getPrecio());
             txtstokventa.setText(""+pro.getStock());
             txtcantidad.requestFocus();
         }else{
              int r;
         r= JOptionPane.showConfirmDialog(this,"producto  no registrado, ¿desea registrar?");
              if (r==0) {
                  productoform cp=new productoform();
         principal.ventanaprincipal.add(cp);
                  cp.setVisible(true);
                  
              }else{
                
              }
           
     }
     
     }
 
  }
   
    
    void buscarCliente(){
    int r;
    String cod=txtcodcliente.getText();
      if (txtcodcliente.getText().equals("")) {
          JOptionPane.showMessageDialog(this,"ingrese el codigo del cliente");
        
    }else{
       cliente=cdao.BuscarCliente(cod);
          if (cliente.getIdentificacion()!=null) {
               
            txtclienteventa.setText(""+cliente.getNombre());
              txtcodprod.requestFocus();
          }else{
          
         r= JOptionPane.showConfirmDialog(this,"cliente no registrado, ¿desea registrar?");
              if (r==0) {
                  clienteform cf=new clienteform();
         principal.ventanaprincipal.add(cf);
                  cf.setVisible(true);
                  
              }else{
                
              }
          }
      
      
      
      }
    
    
    
}
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagreventa;
    private javax.swing.JButton btnbuscliventa;
    private javax.swing.JButton btnbusprodven;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btngeventa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabladetalle;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtclienteventa;
    private javax.swing.JTextField txtcodcliente;
    private javax.swing.JTextField txtcodprod;
    private javax.swing.JTextField txtfechaventa;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtprodventa;
    private javax.swing.JTextField txtserie;
    private javax.swing.JTextField txtstokventa;
    private javax.swing.JTextField txttotalpagar;
    private javax.swing.JTextField txtvendedor;
    // End of variables declaration//GEN-END:variables

 private  void Rpdf() throws FileNotFoundException, DocumentException, IOException{
        
    String id= vtdao.idventa();
    Document documento=new Document();
    File file = new File ("Documentos,NetBeansProjects,SistemaVentaSena,venta"+id+".pdf");
    FileOutputStream ficheropdf= new FileOutputStream( file);
    PdfWriter.getInstance(documento, ficheropdf);
    
    documento.open();
    
    Paragraph titulo= new Paragraph("FACTURA DE VENTA OLIVO VERDE LA 4 \n\n",
    
            FontFactory.getFont("arial",
                    
                    22,
                    Font.BOLD,
                    BaseColor.BLACK
                    )
    
    );
    documento.add(titulo);
  
  Paragraph fecha= new Paragraph();
  fecha.add(Chunk.NEWLINE);
  Date date=new Date();
  fecha.add("FACTURA No:"+id+"\n\nFECHA:"+ new SimpleDateFormat("dd-MM-yyyy").format(date)+"\n\n");
  fecha.setAlignment(Element.ALIGN_RIGHT);
  
  documento.add(fecha);
    Paragraph encabezado= new Paragraph();
    
    String ruc="110544045";
    String nombre= "olivo verde";
    String direccion="clle 4 #58a17";
    String telefono="3204126504";
 
    encabezado.add("RUT:" +  ruc+ "\n\n NOMBRE DE LA EMPRESA:"  +nombre+ "\n\n DIRECCION:" +    direccion+"\n\n TELEFONO:" +   telefono );
    documento.add(encabezado);
    Paragraph cli= new Paragraph();
    cli.add(Chunk.NEWLINE);
    cli.add("DATO DEL CLIENTE:"+"\n\n");
    
   documento.add(cli);
   
   PdfPTable tablacli= new PdfPTable(2);
            
    tablacli.setWidthPercentage(100);
    tablacli.getDefaultCell().setBorder(0);
    float[]Columnacli= new float[]{20f, 30f};
    tablacli.setWidths(Columnacli);
    tablacli.setHorizontalAlignment(Element.ALIGN_LEFT);
        PdfPCell cl1= new PdfPCell(new Phrase("identificacion:"));
        PdfPCell cl2= new PdfPCell(new Phrase("Nombre:"));
      
        cl1.setBorder(0);
        cl2.setBorder(0);
       
        tablacli.addCell(cl1);
        tablacli.addCell(cl2);
       
        tablacli.addCell(txtcodcliente.getText());
        tablacli.addCell(txtclienteventa.getText());
       
        
        
        documento.add(tablacli);
        
        
        //se agrega la tabla de los productos
        
        PdfPTable tablapro= new PdfPTable(4);
            
    tablapro.setWidthPercentage(100);
    tablapro.getDefaultCell().setBorder(0);
    float[]Columnapro= new float[]{20f, 50f, 40f, 30f};
    tablapro.setWidths(Columnapro);
    tablapro.setHorizontalAlignment(Element.ALIGN_LEFT);
        PdfPCell pro1= new PdfPCell(new Phrase("cantidad.",  FontFactory.getFont("arial",
                    
                    14,
                    Font.BOLD,
                    BaseColor.BLUE)));
        PdfPCell pro2= new PdfPCell(new Phrase("Descripcion:",  FontFactory.getFont("arial",
                    
                    14,
                    Font.BOLD,
                    BaseColor.BLUE)));
        PdfPCell pro3= new PdfPCell(new Phrase("precio U:",  FontFactory.getFont("arial",
                    
                    14,
                    Font.BOLD,
                    BaseColor.BLUE)));
        PdfPCell pro4= new PdfPCell(new Phrase(" precio Total:",  FontFactory.getFont("arial",
                    
                    14,
                    Font.BOLD,
                    BaseColor.BLUE)));
        pro1.setBorder(0);
        pro2.setBorder(0);
        pro3.setBorder(0);
        pro4.setBorder(0);
        tablapro.addCell(pro1);
        tablapro.addCell(pro2);
        tablapro.addCell(pro3);
        tablapro.addCell(pro4);
        
        
        for (int i = 0; i < tabladetalle.getRowCount(); i++) {
            String producto= tabladetalle.getValueAt(i, 2).toString();
            String cantidad= tabladetalle.getValueAt(i, 3).toString();
              String precio= tabladetalle.getValueAt(i, 4).toString();
               String total= tabladetalle.getValueAt(i, 5).toString();
            
        tablapro.addCell(cantidad);
        tablapro.addCell(producto);
        tablapro.addCell(precio);
        tablapro.addCell(total);
        
        
        }
        
    documento.add(tablapro);
    
    Paragraph info= new Paragraph();
    String total=txttotalpagar.getText();
    info.add(Chunk.NEWLINE);
    info.add("TOTAL A PAGAR:"+ total);
    info.setAlignment(Element.ALIGN_RIGHT);
      
    documento.add(info);
    
    Paragraph firma= new Paragraph();
    firma.add(Chunk.NEWLINE);
    firma.add("cancelacion y firma");
    firma.add("---------------------------");
    firma.setAlignment(Element.ALIGN_CENTER);
    documento.add(firma);
    
    
    Paragraph mensaje= new Paragraph();
    mensaje.add(Chunk.NEWLINE);
    
    mensaje.add("GRACIAS POR SU COMPRA");
    mensaje.setAlignment(Element.ALIGN_CENTER);
    documento.add(mensaje);
    
    
    documento.close();
        Desktop.getDesktop().open(file );
    
    
    
        }

    }




